### PR TITLE
Ensure that EclipseJavaCompiler doesn't pass duplicate source files to ECJ

### LINKED ISSUE #229: ECJ: Duplicate source files with generated sources when compiling without `clean`
Using latest `plexus-compiler-eclipse` (and `ecj`), when changing a java file and just compiling without `clean`, I'm getting:
```
Compilation failure
Unknown source: java.lang.IllegalArgumentException: File /home/foo/target/generated-sources/annotations/foo/SomeMapperImpl.java is specified more than once
```
The mapper is generated via mapstruct.

When adding `-X` I can see here that the file is indeed passed twice to ECJ:
https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.12.0/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L357

Cause:
- file is added initially here (as expected): https://github.com/codehaus-plexus/plexus-compiler/blob/plexus-compiler-2.12.0/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L247
- but it is added again via `addExtraSources()`: https://github.com/codehaus-plexus/plexus-compiler/blob/f6c899b76e18ef6039965ea06039a84fd0604417/plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java#L628-L638

Potential fix: use `Set` or make `addExtraSources()` more intelligent.

### PR DESCRIPTION
**Pull request by famod**
Fixes #229

I tried setting excludes for `DirectoryScanner`, but `allSources` contains absolute paths at that point, making it unecessarily complicated.
Also, checking whether `allSources` already contains a file would require frequent iterations of that list (or another helper `Set`).

### CODE REVIEW

File: plexus-compilers/plexus-compiler-eclipse/src/test/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompilerTest.java [hunk 1]
```diff
@@ -14,42 +15,42 @@
 {
     @ParameterizedTest
     @MethodSource( "sources" )
-    void testReorderedSources( List<String> expected, List<String> inputSources )
+    void testReorderedSources( LinkedHashSet<String> expected, LinkedHashSet<String> inputSources )
```
Comment (olamy) [inline plexus-compilers/plexus-compiler-eclipse/src/test/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompilerTest.java:18]: definitely a nit comment (sorry for that): maybe using Set rather than the implementation?

**Comment by olamy** [comment]
@famod thanks for the PR

**Comment by famod** [comment]
Ironically, this will become obsolete with the upcoming change for fixing the following issue: https://github.com/codehaus-plexus/plexus-compiler/discussions/231#discussioncomment-3110434
