### PR TITLE
Correctly determine the version of the underlying javac tool

### LINKED ISSUE #356: Incorrect semantics of JavacCompiler.isPreJavaXX
According to the javadoc of https://github.com/codehaus-plexus/plexus-compiler/blob/c5edddc7deaf32d966db3262dfde21c565d51e25/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L410 and https://github.com/codehaus-plexus/plexus-compiler/blob/c5edddc7deaf32d966db3262dfde21c565d51e25/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L393 the methods `isPreJavaXX` are supposed to

> return true if the compiler configuration represents a Java XX compiler or later, false otherwise

The logic within those methods evaluates partially also the parameter `source` (https://github.com/codehaus-plexus/plexus-compiler/blob/c5edddc7deaf32d966db3262dfde21c565d51e25/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L418) or `release` (https://github.com/codehaus-plexus/plexus-compiler/blob/c5edddc7deaf32d966db3262dfde21c565d51e25/plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java#L435) which are completely orthogonal to the javac version being used. They only determine the bytecode version being generated but have nothing to do with the version of the compiler itself.

However I am not sure when `CompilerConfiguration.getCompilerVersion()` is reliably set at all. IMHO there should be some logic separate for in-process and forked compiling which determines the real `javac` version (either from system property `java.version` for in-process compilation or the parsed output of `javac -version`)

### PR DESCRIPTION
**Pull request by kwin**
Ignore CompilerConfiguration values as they are unreliable (and don't represent the used javac version)
Make test execution more resilient by interpolating settings.xml correctly and make sure commons-lang 2.0 is resolved prior to unit testing

This closes #356

### CODE REVIEW

File: plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java [hunk 1]
```diff
@@ -128,6 +133,39 @@ public String getCompilerId() {
         return "javac";
     }
 
+    private String getInProcessJavacVersion() throws CompilerException {
+        return System.getProperty("java.version");
+    }
+
+    private String getOutOfProcessJavacVersion(String executable) throws CompilerException {
```
Comment (slawekjaranowski) [inline plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:140]: I would like to consider caching an output of additional external executable. 
It can take a notable time especially in multi module projects.

We can simply build a static map executable to version.

Comment (kwin) [reply plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:144]: Fixed in https://github.com/codehaus-plexus/plexus-compiler/pull/357/commits/37195795d24d0e6a09e493b65d1901233329ba98.

File: plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java [hunk 2]
```diff
@@ -128,6 +137,44 @@ public String getCompilerId() {
...
+        String version = VERSION_PER_EXECUTABLE.get(executable);
```
Comment (slawekjaranowski) [inline plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:145]: `computeIfAbsent` ?

Comment (kwin) [reply plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:145]: tricky because of the checked exception which might be thrown there.

Comment (slawekjaranowski) [reply plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:145]: so use simple HashMap and synchronize access in code

Comment (kwin) [reply plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:145]: possible, not sure if the additional complexity is worth it. Do you have a strong opinion about it?

Comment (slawekjaranowski) [reply plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java:145]: > possible, not sure if the additional complexity is worth it. Do you have a strong opinion about it?

Ok, can be simple, at most there will be a few execution for version

**Review by slawekjaranowski — APPROVED** [review]
